###LOCALHOST REQUESTS

### Movies ###

### Get all movies
GET http://localhost:3000/movies

### Get a movie by id
GET http://localhost:3000/movies/667dd40f27603bafcf631e13

### Create a movie
POST http://localhost:3000/movies
Content-Type: application/json

    {
        "title": "The Matrix",
        "year": 1999,
        "director": "The Wachowskis",
        "duration": 135,
        "poster": "https://image.tmdb.org/t/p/w500/2uNldM0v8l1ah5zS1ISq8w7e9v9.jpg",
        "rate": 8.5,
        "genre": ["Action", "Sci-Fi", "Thriller"]
    }

### Update a movie
PUT http://localhost:3000/movies/667dd40f27603bafcf631e15
Content-Type: application/json

    {
        "title": "The Matrix III",
        "year": 2001,
        "director": "The Wachowskis",
        "duration": 135,
        "poster": "https://image.tmdb.org/t/p/w500/2uNldM0v8l1ah5zS1ISq8w7e9v9.jpg",
        "rate": 8.5,
        "genre": ["Action", "Sci-Fi", "Thriller"]
    }

### Delete a movie
DELETE http://localhost:3000/movies/667dd40f27603bafcf631e15

### Books ###

### Get all books
GET http://localhost:3000/books

### Get a book by id
GET http://localhost:3000/books/667dce8927603bafcf631e01

### Create a book
POST http://localhost:3000/books
Content-Type: application/json

    {
        "title": "Test",
        "release_year": 1999,
        "number_of_pages": 135,
        "author": "Diego V",
        "genre": ["Action", "Science Fiction", "Thriller"],
        "book_cover": "https://m.media-amazon.com/images/I/51M7XGLQTBL._SY466_.jpg"
    }

### Update a book
PUT http://localhost:3000/books/667f28d326b59852074d808d
Content-Type: application/json

    {
        "title": "Test Test",
        "release_year": 1999,
        "number_of_pages": 135,
        "author": "Diego Vasquez",
        "genre": ["Action", "Science Fiction", "Thriller"],
        "book_cover": "https://m.media-amazon.com/images/I/51M7XGLQTBL._SY466_.jpg"
    }

### Delete a book
DELETE http://localhost:3000/books/667f28d326b59852074d808d